### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DmitryFalse** [Alex3434/wmi-static-spoofer#2]
http://prntscr.com/ltm31o

=================================

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	warning treated as error - no 'object' file generated	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\util.h	15	
Warning	C4018	'<=': signed/unsigned mismatch	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\util.h	15	
Warning	C4047	'=': 'RaidUnitRegisterInterfaces' differs in levels of indirection from 'UINT64'	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\spoofer.h	29	
Warning	C4047	'=': 'UINT64' differs in levels of indirection from 'PVOID'	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\util.h	184	
Warning	C4100	'DriverObject': unreferenced formal parameter	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\main.c	6	
Warning	C4047	'function': 'char *' differs in levels of indirection from 'CHAR (*)[32]'	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\spoofer.h	50	
Warning	C4047	'function': 'const char *' differs in levels of indirection from 'CHAR (*)[256]'	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\util.h	186	
Warning	C4024	'randstring': different types for formal and actual parameter 1	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\spoofer.h	50	
Warning	C4100	'RegistryPath': unreferenced formal parameter	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\main.c	14	
Warning	C4189	'status': local variable is initialized but not referenced	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\spoofer.h	37	
Warning	C4024	'strstr': different types for formal and actual parameter 1	wmic_static_spoofer	c:\users\dmitryfals3r\desktop\da\wmi-static-spoofer-master\wmic_static_spoofer\util.h	186	
Warning	wpp	-scan found no begin_wpp blocks. Rescanning as INI file. This behavior will be removed in a future release.	wmic_static_spoofer	C:\Users\DmitryFals3R\Desktop\da\wmi-static-spoofer-master\WMIC_static_spoofer\trace.h	1

**Comment by Alex3434** [comment]
"Error C2220 warning treated as error"
Open project properties --> C/C++ --> General --> Treat Warnings as Errors: No (/WX-)
or 
Fix all the Warnings below an rebuild.
