### ISSUE TITLE
Version 1809 (OS Build 17763.253)

### ISSUE THREAD

**Issue by ahmetabdi** [Alex3434/wmi-static-spoofer#6]
Is there any way to make this generic to any windows version?

Currently not working on Version 1809 (OS Build 17763.253)

![ye5wvyk](https://user-images.githubusercontent.com/778015/51065686-1766cb80-15fe-11e9-8a8d-b3fc64855b10.png)

**Comment by Alex3434** [comment]
I will maybe update the project to a newer windows version.
The intention of this project is showing that I works and how it works thats why I didn't release a binary or made it universal across versions of windows.
